### ISSUE TITLE
Serveri vdes pas nje fare kohe

### ISSUE THREAD

**Issue by tpllaha** [tiranacode/jap-jete-admin#17]
Ka mundesi qe te ndodhi vetem ne debug mode, po duhet investiguar me shume. 

ndoshta ndodh ndonje network problem dhe serveri crash, mirepo upstart nuk e ringjall sepse eshte duke watch reloader-in ne vend te vete serverit. 

Ky eshte log i fundit heren e fundit qe ndodhi. 

```
222.186.34.155 - - [07/Mar/2016 06:58:12] "GET https://m.baidu.com/ HTTP/1.1" 200 -
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
79.171.53.100 - - [07/Mar/2016 08:30:45] "POST /api/v1/login/ HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('169.229.3.91', 39136)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 217, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 251, in handle_one_request
    elif self.parse_request():
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 281, in parse_request
    "Bad HTTP/0.9 request type (%r)" % command)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 364, in send_error
    self.log_error("code %d, message %s", code, message)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 273, in log_error
    self.log('error', *args)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 279, in log
    _log(type, '%s - - [%s] %s\n' % (self.address_string(),
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 267, in address_string
    return self.environ['REMOTE_ADDR']
AttributeError: 'WSGIRequestHandler' object has no attribute 'environ'
----------------------------------------
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
46.252.38.173 - - [07/Mar/2016 10:58:00] "POST /api/v1/login/ HTTP/1.1" 200 -
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
46.252.38.173 - - [07/Mar/2016 10:58:05] "POST /api/v1/login/ HTTP/1.1" 200 -
51.254.44.137 - - [07/Mar/2016 14:22:32] "GET / HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('200.54.96.106', 17422)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 217, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 248, in handle_one_request
    self.raw_requestline = self.rfile.readline()
IOError: [Errno 104] Connection reset by peer
----------------------------------------
137.226.113.7 - - [07/Mar/2016 16:12:34] "GET / HTTP/1.0" 200 -
/usr/local/lib/python2.7/dist-packages/werkzeug/filesystem.py:63: BrokenFilesystemWarning: Detected a misconfigured UNIX filesystem: Will use UTF-8 as filesystem encoding instead of 'ANSI_X3.4-1968'
  BrokenFilesystemWarning)
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 194, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 185, in execute
    write(data)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 166, in write
    self.wfile.write(data)
IOError: [Errno 104] Connection reset by peer
```

**Comment by ani12321** [comment]
Solved [commit](https://github.com/tiranacode/jap-jete-admin/commit/057d66c86c52cc3df0f7ddc13d5daf78b514b8df)
